# Generated by Django 3.0.4 on 2020-06-27 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200627_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='privacy',
        ),
        migrations.AddField(
            model_name='collections',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contains',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='collections',
            name='collection_type',
            field=models.CharField(choices=[('Main', 'MAIN'), ('Named', 'NAMED'), ('Finished', 'FINISHED')], default='Main', max_length=10),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(blank=True, default='default_review_text'),
        ),
    ]
