# Generated by Django 3.0.4 on 2020-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200627_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_synopsis',
            field=models.TextField(default='default_book_synopsis'),
        ),
    ]
